### ISSUE TITLE
How do I configure this?

### ISSUE THREAD

**Issue by instinxx** [elytra/BTFU#9]
This is my dir structure:

http://imgur.com/a/2LXoa

This is my config:
https://pastebin.com/BXgR7wrU

Im using MC 1.10.2
Im using BTFU 1.9.4-2.2

I keep receiving an error that it cannot find my backup file. Can you please document the setup better?

**Comment by alexbobp** [comment]
I am not seeing the surrounding directory structure.  is / in that picture the root directory tree of your system?  Probably not.  You can use the absolute path (eg, C:/Users/.../folder on windows, or typically /home/.../folder on linux), or in this case since you have the server and backups directory in the same folder, you could use a relative path, ../BTFUBackup.  My advice is to use an absolute path, to prevent mistakes such as running a copy of your minecraft server.

Feel free to reopen if that didn't help.

**Comment by instinxx** [comment]
Since this is a running on a server host (AKLIZ) I do not have access beyond the directory structure you see. I have set a relative path as =../BTFUBackup and I receive Backups directory does not exist.  Configure it in BTFU.cfg.
As you can imagine, that error is somewhat frustrating. Can you add code that will print what it thinks the absolute path is?

**Comment by instinxx** [comment]
I have found that I have a mod (bdlib) that prints the absolute path in the log. I have tried that as well and BTFU still complains that it cannot find the dir.

**Comment by phit** [comment]
I would ask your provider support, they probably have some kind of filesystem protection so you can't access folders. Also since they have their own daily backup system, looking at their plans, I doubt they are happy with you using lots of filesystem space for your own backup solution.

**Comment by instinxx** [comment]
@phit I am aware of my hosts builtin yet completely unsuitable 1 backup per 24 hour, but I will be moving my backups offsite via FTP to deal with that. However thank you for your comment. Hopefully Alexbobp works to make this mod a bit more user friendly as the idea is sound.

**Comment by alexbobp** [comment]
Maybe.  Before we assume my mod is not user friendly, we should eliminate other possibilities (including whether your hosting provider disallows this).  Is custom-minecraft the *root* of your minecraft server, or is there a deeper directory tree inside?

From phit's quote, they say "coordinate with support beforehand" and "most backup plugins tend to use disk space in an inefficient manner."  We have here a backup plugin that uses disk space in an efficient manner, so that should make them happy.  My advice, since your hosting provider seems to want this sort of thing cleared with them, is to contact them and ask for a backup destination location, and ask for the absolute path to that location for your configuration.

**Comment by alexbobp** [comment]
I will reopen this until we're pretty sure your problem is solved.

I just noticed you mentioned plans to copy the backups offsite with FTP.  I should warn you that BTFU's space-saving is based on filesystem-level hardlinks.  If you want to sync your backups to another system and preserve the space-saving, you would want to use rsync with the -H flag, or another syncing tool that can preserve hardlinks.  FTP will download each snapshot individually and leave you with a huge amount of space taken up wherever you copy the backups to, unless you run a deduplication tool at that end (and it would still waste a lot of bandwidth to copy those backups).
